name: Deploy hello-prod
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        default: latest
        type: string

jobs:
  run:
    name: Deploy hello-prod
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: mozilla-it/gha-deploy-test/projects/hellp-world/actions/deploy-prod@master
      with:
        image_tag: ${{ github.event.inputs.image_tag }}
